spring.application.name=Login_practica_CRE_backend

# ===============================
# Configuración de Aiven MySQL
# ===============================
# Cambiamos localhost por el hostname de Aiven y el puerto 19452
spring.datasource.url=jdbc:mysql://login-idati-login-idati.a.aivencloud.com:19452/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_DRPpHurkZqTbFjaWtNu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Correo Gmail SMTP
# Puerto 587 es el est�ndar para SMTP con STARTTLS
# Puerto 465 ser�a para SSL directo
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Contrase�a de aplicaci�n generada en Google
spring.mail.username=ruizjeisonf@gmail.com
# NO es tu contrase�a normal de Gmail
spring.mail.password=bgqh vunh lkxs ltlj

# Requiere autenticaci�n para enviar correos
spring.mail.properties.mail.smtp.auth=true
# STARTTLS: inicia la conexi�n sin cifrado y la eleva a cifrada
spring.mail.properties.mail.smtp.starttls.enable=true
# Es el mecanismo de seguridad que usa Gmail en el puerto 587
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# JPA / Hibernate
# ===============================
# IMPORTANTE: Cambia 'validate' a 'update' la primera vez para que 
# Hibernate cree las tablas en Aiven automáticamente.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true